/**
 * OpenAI Whisper APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, unknown } from '../schema';

export interface BodyTranscribeFile2srtGetSrtPost {
  audioFile: NodeJS.ReadableStream | Blob;
}

export const bodyTranscribeFile2srtGetSrtPostSchema: Schema<BodyTranscribeFile2srtGetSrtPost> = object(
  { audioFile: ['audio_file', unknown()] }
);
