/**
 * OpenAI Whisper APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, unknown } from '../schema';

export interface BodyTranscribeFileAsrPost {
  audioFile: NodeJS.ReadableStream | Blob;
}

export const bodyTranscribeFileAsrPostSchema: Schema<BodyTranscribeFileAsrPost> = object(
  { audioFile: ['audio_file', unknown()] }
);
