/**
 * OpenAI Whisper APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaskEnum
 */
export enum TaskEnum {
  Transcribe = 'transcribe',
  Translate = 'translate',
}

/**
 * Schema for TaskEnum
 */
export const taskEnumSchema: Schema<TaskEnum> = stringEnum(TaskEnum);
