/**
 * OpenAI Whisper APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema';

export interface ValidationError {
  loc: unknown[];
  msg: string;
  type: string;
}

export const validationErrorSchema: Schema<ValidationError> = object({
  loc: ['loc', array(unknown())],
  msg: ['msg', string()],
  type: ['type', string()],
});
