/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { RoleEnum, roleEnumSchema } from './roleEnum';

export interface ChatCompletionResponseMessage {
  role: RoleEnum;
  /** The contents of the message */
  content: string;
}

export const chatCompletionResponseMessageSchema: Schema<ChatCompletionResponseMessage> = object(
  { role: ['role', roleEnumSchema], content: ['content', string()] }
);
