/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateTranscriptionResponse {
  text: string;
}

export const createTranscriptionResponseSchema: Schema<CreateTranscriptionResponse> = object(
  { text: ['text', string()] }
);
