/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface CreateImageRequest {
  /** A text description of the desired image(s). The maximum length is 1000 characters. */
  prompt: string;
  /** The number of images to generate. Must be between 1 and 10. */
  n?: number | null;
  size?: unknown;
  responseFormat?: unknown;
  /** A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids). */
  user?: string;
}

export const createImageRequestSchema: Schema<CreateImageRequest> = object({
  prompt: ['prompt', string()],
  n: ['n', optional(nullable(number()))],
  size: ['size', optional(unknown())],
  responseFormat: ['response_format', optional(unknown())],
  user: ['user', optional(string())],
});
