/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateTranslationResponse {
  text: string;
}

export const createTranslationResponseSchema: Schema<CreateTranslationResponse> = object(
  { text: ['text', string()] }
);
