/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema } from '../schema';
import { Datum, datumSchema } from './datum';

export interface ImagesResponse {
  created: number;
  data: Datum[];
}

export const imagesResponseSchema: Schema<ImagesResponse> = object({
  created: ['created', number()],
  data: ['data', array(lazy(() => datumSchema))],
});
