/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RoleEnum
 */
export enum RoleEnum {
  System = 'system',
  User = 'user',
  Assistant = 'assistant',
}

/**
 * Schema for RoleEnum
 */
export const roleEnumSchema: Schema<RoleEnum> = stringEnum(RoleEnum);
