/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SizeEnum
 */
export enum SizeEnum {
  Enum256x256 = '256x256',
  Enum512x512 = '512x512',
  Enum1024x1024 = '1024x1024',
}

/**
 * Schema for SizeEnum
 */
export const sizeEnumSchema: Schema<SizeEnum> = stringEnum(SizeEnum);
