/**
 * OpenAI APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface Usage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

export const usageSchema: Schema<Usage> = object({
  promptTokens: ['prompt_tokens', number()],
  completionTokens: ['completion_tokens', number()],
  totalTokens: ['total_tokens', number()],
});
