/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Button, buttonSchema } from './button';
import { Section, sectionSchema } from './section';

export interface Action {
  /** Required for List Messages. Button content. It cannot be an empty string and must be unique within the message. Emojis are supported, markdown is not. */
  button?: string;
  /** Required for Reply Buttons. You can have up to 3 buttons. You cannot have leading or trailing spaces when setting the ID. */
  buttons?: Button[];
  /** Required for List Messages. */
  sections?: Section[];
}

export const actionSchema: Schema<Action> = object({
  button: ['button', optional(string())],
  buttons: ['buttons', optional(array(lazy(() => buttonSchema)))],
  sections: ['sections', optional(array(lazy(() => sectionSchema)))],
});
