/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  PersonalInformationTypeEnum,
  personalInformationTypeEnumSchema,
} from './personalInformationTypeEnum';

export interface Address {
  /** Street number and name */
  street?: string;
  /** City name. */
  city?: string;
  /** State abbreviation. */
  state?: string;
  /** ZIP code. */
  zip?: string;
  /** Full country name. */
  country?: string;
  /** Two-letter country abbreviation. */
  countryCode?: string;
  type?: PersonalInformationTypeEnum;
}

export const addressSchema: Schema<Address> = object({
  street: ['street', optional(string())],
  city: ['city', optional(string())],
  state: ['state', optional(string())],
  zip: ['zip', optional(string())],
  country: ['country', optional(string())],
  countryCode: ['country_code', optional(string())],
  type: ['type', optional(personalInformationTypeEnumSchema)],
});
