/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Body {
  /** The body content of the message. Emojis and markdown are supported. Links are supported. */
  text: string;
}

export const bodySchema: Schema<Body> = object({ text: ['text', string()] });
