/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ButtonReply {
  /** Unique identifier for your button. This ID is returned in the webhook when the button is clicked by the user. */
  id: string;
  /** Button title. It cannot be an empty string and must be unique within the message. Emojis are supported, markdown is not. */
  title: string;
}

export const buttonReplySchema: Schema<ButtonReply> = object({
  id: ['id', string()],
  title: ['title', string()],
});
