/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Button {
  type: string;
  /** Button title. It cannot be an empty string and must be unique within the message. Emojis are supported, markdown is not. */
  title?: string;
  /** Unique identifier for your button. This ID is returned in the webhook when the button is clicked by the user. */
  id?: string;
}

export const buttonSchema: Schema<Button> = object({
  type: ['type', string()],
  title: ['title', optional(string())],
  id: ['id', optional(string())],
});
