/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  ButtonParameterTypeEnum,
  buttonParameterTypeEnumSchema,
} from './buttonParameterTypeEnum';

export interface ButtonParameter {
  type: ButtonParameterTypeEnum;
  /** Required for quick_reply buttons. Developer-defined payload that is returned when the button is clicked in addition to the display text on the button. */
  payload?: string;
  /** Required for URL buttons. Developer-provided suffix that is appended to the predefined prefix URL in the template. */
  text?: string;
}

export const buttonParameterSchema: Schema<ButtonParameter> = object({
  type: ['type', buttonParameterTypeEnumSchema],
  payload: ['payload', optional(string())],
  text: ['text', optional(string())],
});
