/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string, unknown } from '../schema';
import {
  ComponentTypeEnum,
  componentTypeEnumSchema,
} from './componentTypeEnum';
import { SubTypeEnum, subTypeEnumSchema } from './subTypeEnum';

export interface Component {
  type: ComponentTypeEnum;
  subType?: SubTypeEnum;
  /** Required when type=button. Array of parameter objects with the content of the message. For components of type=button, see the button parameter object. */
  parameters: unknown[];
  /** Required when type=button. Not used for the other types. Position index of the button. You can have up to 3 buttons using index values of 0 to 2. */
  index?: string;
}

export const componentSchema: Schema<Component> = object({
  type: ['type', componentTypeEnumSchema],
  subType: ['sub_type', optional(subTypeEnumSchema)],
  parameters: ['parameters', array(unknown())],
  index: ['index', optional(string())],
});
