/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ComponentTypeEnum
 */
export enum ComponentTypeEnum {
  Header = 'header',
  Body = 'body',
  Button = 'button',
}

/**
 * Schema for ComponentTypeEnum
 */
export const componentTypeEnumSchema: Schema<ComponentTypeEnum> = stringEnum(ComponentTypeEnum);
