/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Currency {
  /** Default text if localization fails. */
  fallbackValue: string;
  /** Currency code as defined in ISO 4217. */
  code: string;
  /** Amount multiplied by 1000. */
  amount1000: number;
}

export const currencySchema: Schema<Currency> = object({
  fallbackValue: ['fallback_value', string()],
  code: ['code', string()],
  amount1000: ['amount_1000', number()],
});
