/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface DateTimeObject {
  /** Default text. For Cloud API, we always use the fallback value, and we do not attempt to localize using other optional fields. */
  fallbackValue: string;
  dayOfWeek?: number;
  year?: number;
  month?: number;
  dayOfMonth?: number;
  hour?: number;
  minute?: number;
  calendar?: string;
}

export const dateTimeObjectSchema: Schema<DateTimeObject> = object({
  fallbackValue: ['fallback_value', string()],
  dayOfWeek: ['day_of_week', optional(number())],
  year: ['year', optional(number())],
  month: ['month', optional(number())],
  dayOfMonth: ['day_of_month', optional(number())],
  hour: ['hour', optional(number())],
  minute: ['minute', optional(number())],
  calendar: ['calendar', optional(string())],
});
