/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  PersonalInformationTypeEnum,
  personalInformationTypeEnumSchema,
} from './personalInformationTypeEnum';

export interface EmailObject {
  email?: string;
  type?: PersonalInformationTypeEnum;
}

export const emailObjectSchema: Schema<EmailObject> = object({
  email: ['email', optional(string())],
  type: ['type', optional(personalInformationTypeEnumSchema)],
});
