/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Image {
  /** The media object ID. Required when you are not using a link. */
  id?: string;
  /** The protocol and URL of the media to be sent. Use only with HTTP/HTTPS URLs. Required when you are not using an uploaded media ID. */
  link?: string;
  /** Describes the specified image media. */
  caption?: string;
}

export const imageSchema: Schema<Image> = object({
  id: ['id', optional(string())],
  link: ['link', optional(string())],
  caption: ['caption', optional(string())],
});
