/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InteractiveTypeEnum
 */
export enum InteractiveTypeEnum {
  List = 'list',
  Button = 'button',
}

/**
 * Schema for InteractiveTypeEnum
 */
export const interactiveTypeEnumSchema: Schema<InteractiveTypeEnum> = stringEnum(InteractiveTypeEnum);
