/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Language {
  /** The code of the language or locale to use. Accepts both language and language_locale formats (e.g., en and en_US). */
  code: string;
  /** The language policy the message should follow. */
  policy?: string;
}

export const languageSchema: Schema<Language> = object({
  code: ['code', string()],
  policy: ['policy', optional(string())],
});
