/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Location {
  /** Latitude of the location. */
  latitude: string;
  /** Longitude of the location. */
  longitude: string;
  /** Name of the location. */
  name?: string;
  /** Address of the location. Only displayed if name is present. */
  address?: string;
}

export const locationSchema: Schema<Location> = object({
  latitude: ['latitude', string()],
  longitude: ['longitude', string()],
  name: ['name', optional(string())],
  address: ['address', optional(string())],
});
