/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Audio, audioSchema } from './audio';
import { Contact, contactSchema } from './contact';
import { Document, documentSchema } from './document';
import { Image, imageSchema } from './image';
import { Interactive, interactiveSchema } from './interactive';
import { Location, locationSchema } from './location';
import { MessageTypeEnum, messageTypeEnumSchema } from './messageTypeEnum';
import { Sticker, stickerSchema } from './sticker';
import { Template, templateSchema } from './template';
import { Text, textSchema } from './text';
import { Video, videoSchema } from './video';

export interface Message {
  audio?: Audio;
  /** A contact object. Required when type=contacts. */
  contacts?: Contact[];
  document?: Document;
  image?: Image;
  interactive?: Interactive;
  location?: Location;
  /** Messaging service used for the request. */
  messagingProduct: string;
  /** Currently, you can only send messages to individuals. */
  recipientType?: string;
  sticker?: Sticker;
  template?: Template;
  text?: Text;
  /** WhatsApp ID or phone number for the person you want to send a message to. */
  to: string;
  type?: MessageTypeEnum;
  video?: Video;
}

export const messageSchema: Schema<Message> = object({
  audio: ['audio', optional(lazy(() => audioSchema))],
  contacts: ['contacts', optional(array(lazy(() => contactSchema)))],
  document: ['document', optional(lazy(() => documentSchema))],
  image: ['image', optional(lazy(() => imageSchema))],
  interactive: ['interactive', optional(lazy(() => interactiveSchema))],
  location: ['location', optional(lazy(() => locationSchema))],
  messagingProduct: ['messaging_product', string()],
  recipientType: ['recipient_type', optional(string())],
  sticker: ['sticker', optional(lazy(() => stickerSchema))],
  template: ['template', optional(lazy(() => templateSchema))],
  text: ['text', optional(lazy(() => textSchema))],
  to: ['to', string()],
  type: ['type', optional(messageTypeEnumSchema)],
  video: ['video', optional(lazy(() => videoSchema))],
});
