/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MessageTypeEnum
 */
export enum MessageTypeEnum {
  Text = 'text',
  Audio = 'audio',
  Contacts = 'contacts',
  Document = 'document',
  Image = 'image',
  Interactive = 'interactive',
  Location = 'location',
  Sticker = 'sticker',
  Template = 'template',
  Video = 'video',
}

/**
 * Schema for MessageTypeEnum
 */
export const messageTypeEnumSchema: Schema<MessageTypeEnum> = stringEnum(MessageTypeEnum);
