/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PersonalInformationTypeEnum
 */
export enum PersonalInformationTypeEnum {
  HOME = 'HOME',
  WORK = 'WORK',
}

/**
 * Schema for PersonalInformationTypeEnum
 */
export const personalInformationTypeEnumSchema: Schema<PersonalInformationTypeEnum> = stringEnum(PersonalInformationTypeEnum);
