/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { PhoneTypeEnum, phoneTypeEnumSchema } from './phoneTypeEnum';

export interface PhoneObject {
  /** Automatically populated with the wa_id value as a formatted phone number. */
  phone?: string;
  /** WhatsApp ID. */
  waId?: string;
  type?: PhoneTypeEnum;
}

export const phoneObjectSchema: Schema<PhoneObject> = object({
  phone: ['phone', optional(string())],
  waId: ['wa_id', optional(string())],
  type: ['type', optional(phoneTypeEnumSchema)],
});
