/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ResponseMessage {
  id: string;
}

export const responseMessageSchema: Schema<ResponseMessage> = object({
  id: ['id', string()],
});
