/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RetrieveMediaURL {
  messagingProduct: string;
  url: string;
  mimeType: string;
  sha256: string;
  fileSize: string;
  id: string;
}

export const retrieveMediaURLSchema: Schema<RetrieveMediaURL> = object({
  messagingProduct: ['messaging_product', string()],
  url: ['url', string()],
  mimeType: ['mime_type', string()],
  sha256: ['sha256', string()],
  fileSize: ['file_size', string()],
  id: ['id', string()],
});
