/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Row {
  id: string;
  title: string;
  description?: string;
}

export const rowSchema: Schema<Row> = object({
  id: ['id', string()],
  title: ['title', string()],
  description: ['description', optional(string())],
});
