/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { ResponseContact, responseContactSchema } from './responseContact';
import { ResponseMessage, responseMessageSchema } from './responseMessage';

export interface SendMessageResponse {
  messagingProduct: string;
  contacts: ResponseContact[];
  messages: ResponseMessage[];
}

export const sendMessageResponseSchema: Schema<SendMessageResponse> = object({
  messagingProduct: ['messaging_product', string()],
  contacts: ['contacts', array(lazy(() => responseContactSchema))],
  messages: ['messages', array(lazy(() => responseMessageSchema))],
});
