/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Sticker {
  /** The protocol and URL of the media to be sent. Use only with HTTP/HTTPS URLs. Required when you are not using an uploaded media ID. */
  link?: string;
  /** The media object ID. Required when you are not using a link. */
  id?: string;
}

export const stickerSchema: Schema<Sticker> = object({
  link: ['link', optional(string())],
  id: ['id', optional(string())],
});
