/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubTypeEnum
 */
export enum SubTypeEnum {
  QuickReply = 'quick_reply',
  Url = 'url',
}

/**
 * Schema for SubTypeEnum
 */
export const subTypeEnumSchema: Schema<SubTypeEnum> = stringEnum(SubTypeEnum);
