/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Video {
  /** The protocol and URL of the media to be sent. Use only with HTTP/HTTPS URLs. Required when you are not using an uploaded media ID. */
  link?: string;
  /** Required when you are not using a link. The media object ID. */
  id?: string;
}

export const videoSchema: Schema<Video> = object({
  link: ['link', optional(string())],
  id: ['id', optional(string())],
});
