/**
 * OpenAI Whisper APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { ValidationError } from '../models/validationError';

/**
 * Creates an instance of HTTPValidation
 */
interface HTTPValidation {
  detail?: ValidationError[];
}

export class HTTPValidationError extends ApiError<HTTPValidation> {}
