/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Message, messageSchema } from '../models/message';
import {
  SendMessageResponse,
  sendMessageResponseSchema,
} from '../models/sendMessageResponse';
import { string } from '../schema';
import { BaseController } from './baseController';

export class MessagesController extends BaseController {
  /**
   * Use this endpoint to send text messages, media, message templates to your customers.
   *
   * @param phoneNumberID
   * @param body            To send a message, you must first assemble a message object with the
   *                                          content you want to send.
   * @return Response from the API call
   */
  async sendMessage(
    phoneNumberID: string,
    body: Message,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SendMessageResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      phoneNumberID: [phoneNumberID, string()],
      body: [body, messageSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/${mapped.phoneNumberID}/messages`;
    return req.callAsJson(sendMessageResponseSchema, requestOptions);
  }
}
